type = "webpack"
zone_id = "" # Taken from dash.cloudflare.com (a zone == a domain)
account_id = "" # Taken from dash.cloudflare.com
workers_dev = true
webpack_config = "webpack.config.js"
name = "functions"

[env.test]
name = "ably-cloudflare-workers-test"
vars = { ENVIRONMENT = "test", ABLY_PRIVATE_API_KEY = "UPDATE_THIS_TO_YOUR_ABLY_APPLICATION_KEY" }